
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: opendatahub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: registry.tannerjc.net/echo-server:latest
        ports:
        - containerPort: 8080

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: my-echo-service
  namespace: opendatahub
spec:
  selector:
    app: echo-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---
# HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo-server
  namespace: opendatahub
  labels:
    app: echo-server
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: data-science-gateway
    namespace: openshift-ingress
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /echo
    backendRefs:
    - group: ""
      kind: Service
      name: my-echo-service
      namespace: opendatahub
      port: 8080
      weight: 1