kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth2-client
  namespace: auth2-client
  labels:
    app: oauth2-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-client
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: oauth2-client
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: oauth2-client-nginx-config
            defaultMode: 420
      containers:
        - name: oauth2-client
          image: 'quay.io/gshanmug-quay/oauth2-client:latest3'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-client
  namespace: auth2-client
  labels:
    app: oauth2-client
spec:
  clusterIP: 172.30.151.215
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.151.215
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: oauth2-client
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: oauth2-client
  namespace: auth2-client
spec:
  host: oauth2-client.apps.rosa.gowtham-rosa.pygl.p3.openshiftapps.com
  to:
    kind: Service
    name: oauth2-client
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
