apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - '--provider=keycloak-oidc'
            - '--client-id=oauth2-proxy'
            - '--client-secret=<client-secret>'
            - '--redirect-url=https://oauth2-keycloak.apps.rosa.gowtham-rosa.pygl.p3.openshiftapps.com/oauth2/callback'
            - '--oidc-issuer-url=https://keycloak-helm-dev.apps.rosa.gowtham-rosa.pygl.p3.openshiftapps.com/realms/rhoai-poc'
            - '--email-domain=*'
            - '--cookie-secret=<32-bit-secret>'
            - '--upstream=http://envoy.keycloak.svc.cluster.local:8080'
            - '--http-address=0.0.0.0:4180'
            - '--set-authorization-header=true'
            - '--pass-access-token=true'
            - '--cookie-domain=apps.rosa.gowtham-rosa.pygl.p3.openshiftapps.com'
            - '--session-store-type=redis'
            - '--redis-connection-url=redis://redis:6379'
            - '--pass-user-headers=true'
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  selector:
    app: oauth2-proxy
  ports:
    - port: 80
      targetPort: 4180
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oauth2
  namespace: keycloak
spec:
  to:
    kind: Service
    name: oauth2-proxy
  port:
    targetPort: 4180
  tls:
    termination: edge


