apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: hashicorp/http-echo
          args:
            - "-listen=:5000"
            - "-text=Hello from Service 1"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

