apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: hashicorp/http-echo
          args:
            - "-listen=:5000"
            - "-text=Hello from Service 2"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

